donnes/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('allcommande/',lescommendes,name='allcommande'),
    path('traiter/<int:id>',traiter,name='traiter'),
]

moncompte/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
urlpatterns = [
path('profile/',moncompte,name="moncompte"),
path('supp/<int:id>',supprimer,name='supp'),
path('modif/<int:id>',modifier,name='modif'),
path('changer_photo/',changer_photo,name='changer_photo')
    
]

venips/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('acceuil.urls')),
    path('',include('annonce.urls')),
    path('',include('boutique.urls')),
    path('',include('connexion.urls')),
    path('',include('moncompte.urls')),
    path('',include('donnes.urls')),

    

]
urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

annonce/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from acceuil.models import Clients

# Create your models here.

# model pour les annonces

class Annonces(models.Model):

    choix_type_annonce = [
        ('vetement','vetement'),
        ('chaussure','chaussure'),
        ('chemise','chemise'),
        ('technologie','technologie'),
        ('telephone','telephone'),
        ('ordinateur','ordinateur'),
        ('autre','autre')
    ]


    choix_nature = [
        ('occasion','occasion'),
        ('nouveau','nouveau')
    ]

    desi_annonce = models.CharField(max_length=25,verbose_name="designation d'annonce")    
    prix_annonce = models.PositiveIntegerField()
    img_annonce = models.ImageField(upload_to='media/annonces',default='img',verbose_name="image d'annonce")
    vendeur =models.ForeignKey(Clients,on_delete=CASCADE)
    
    lieu_produit = models.CharField(max_length=45,default='conakry')
    
    nature = models.CharField(max_length=50,default='occasion',choices=choix_nature)
    A_type= models.CharField( max_length=50,default='autre',choices=choix_type_annonce)
    desc_annonce = models.TextField(default='pas de description',verbose_name="description de l'annonce")


    def __str__(self):
        return self.desi_annonce

moncompte/models.py
from django.db import models

# Create your models here.

moncompte/views.py
from django.shortcuts import redirect, render
from acceuil.models import *
from annonce.models import *
from django.contrib.auth.decorators import login_required
from boutique.views import nombre
# Create your views here.
@login_required
def moncompte(request):
    user_connect =request.user
      #permet de recuperer  le nombre dans le pannier et le profil utilisateur
    user = request.user
    user_connect = Clients.objects.get(nomutilisateur=user)
    nombre_les_commande_commendeur=nombre(request)
    try:
        info_user = Clients.objects.get(nomutilisateur=user_connect)
        
        annonce_user=Annonces.objects.filter(vendeur_id=info_user.id)
        print(annonce_user)
    except:
        return redirect('connexion')

   
    return render(request,'moncompte.html',{'info':info_user,'annonce_user':annonce_user,'nbr':nombre_les_commande_commendeur,'user_connect':user_connect})

#la modification d'un annonce par son proprietaire
@login_required
def modifier(request,id):
    user = request.user

    info_vendeur = Clients.objects.get(nomutilisateur=user)
    annonce_modif = Annonces.objects.get(id=id)
      #permet de recuperer  le nombre dans le pannier et le profil utilisateur
    user_connect = Clients.objects.get(nomutilisateur=user)
    nombre_les_commande_commendeur=nombre(request)
    if request.method =='POST':
        desig = request.POST['designation']
        prix = request.POST['prix']
        lieu = request.POST['lieu']
        type = request.POST['type']
        img = request.FILES['img']
        nature = request.POST['nature']
        description = request.POST['description']
     
        annonce_modif.desi_annonce=desig
        annonce_modif.prix_annonce = prix
        annonce_modif.lieu_produit = lieu
        annonce_modif.A_type = type
        annonce_modif.nature = nature
        annonce_modif.desc_annonce = description
        annonce_modif.vendeur = info_vendeur
        annonce_modif.img_annonce = img
        
        annonce_modif.save()
        return redirect('moncompte')       
    return render(request,'modifier.html',{'annonce_modif':annonce_modif,'nbr':nombre_les_commande_commendeur,'user_connect':user_connect})

#la suppression d'un annonce 

def supprimer(request,id):
    annonce_supp = Annonces.objects.get(id=id).delete()

    return redirect('moncompte')


def changer_photo(request):
    user = request.user

    info_vendeur = Clients.objects.get(nomutilisateur=user)
    if request.method =='POST':
        img = request.FILES['profile']
        info_vendeur.profil = img
        info_vendeur.save()
        return redirect('moncompte')
        
        

moncompte/templates/modifier.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Contact
{% endblock %}
{% block content %}

<div class="">
	{% include 'menux.html' %}
</div>

<div class=" container" style="margin-top: 5em;">

	<!-- ========== Start formulaire de changement des information des annonces ========== -->
	<form action="{% url 'modif' annonce_modif.id  %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<label for="designation">Designation</label>
		<input type="text" name="designation" id="" value={{annonce_modif.desi_annonce}} class="form-control">
		<label for="prix">Prix d'annonce</label>
		<input type="number" name="prix" id="" value={{annonce_modif.prix_annonce}} class="form-control">
		<label for="lieu">Lieu du produit</label>
		<input type="text" name="lieu" id="" value={{annonce_modif.lieu_produit}} class="form-control">
		<label for="nature">Nature</label>
		<select name="nature" class="form-control " id="id_nature">
			<option value="occasion">occasion</option>

			<option value="nouveau">nouveau</option>

		</select>
		<label for="type">type</label>
		<select name="type" class="form-control " id="id_A_type">
			<option value="vetement">vetement</option>

			<option value="chaussure">chaussure</option>

			<option value="chemise">chemise</option>

			<option value="technologie">technologie</option>

			<option value="telephone">telephone</option>

			<option value="ordinateur">ordinateur</option>

			<option value="autre" selected>autre</option>
			placeholder="ex:voiture;pour faliciter la recherche">
		</select>
		<label for="img">Image de votre annonce</label>
		<input type="file" name="img" id="" class="form-control">
		<label for="description">la description de l'annonce</label>
		<textarea name="description" id="" cols="30" rows="10"
			class="form-control">{{annonce_modif.desc_annonce}}</textarea>
		<input type="submit" value="changer" class="btn btn-success">
	</form>
	<!-- ========== End formulaire de changement des information des annonces ========== -->

</div>


{% include 'footer.html'%}
{% endblock %}

moncompte/templates/moncompte.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Contact
{% endblock %}
{% block content %}

{% include 'menux.html' %}

<div class="container  " style="margin-top:8em;margin-bottom: 8em;">
  <div class="row">
    <div class="col-lg-4 col-md-4 h-50  text-white "
      style="text-align: center;padding: none; width: 20em;border: 2px solid white">
      <img src="{{ info.profil.url }}" class="img-thumbnail" alt="" width="280px"><br>
      <p class="text-capitalize mt-2">{{ info.nomclient }} {{ info.prenomclient }} </p>
      <p class="btn btn-info" style="width: 18em;" data-bs-toggle="modal" data-bs-target="#exampleModal">Changer
        photo de profile</p>

      <p class="btn btn-primary" style="width: 18em;">Mes Annonces</p>
      <p class="btn btn-danger" style="width: 18em;">Paramettre du compte</p> <br>
      <a href="{% url 'ajout_annonce' %}" class="">Ajouter des Annonces </a> <br>


    </div>
    <div class="col-lg-8 col-md-8">
      <span class="text-capitalize mt-2">{{ info.nomclient }} {{ info.prenomclient }} </p>
        <span>nom utilisateur : {{ info.nomutilisateur }}</span><br>
        <span>mon Email : {{ info.emailclient }}</span><br>
        <span>nom utilisateur : {{ info.numero }}</span><br>


        <p class="bg-primary text-center mt-2 text-white">Mes annonces</p>
        <div class="row">

          {% for i in annonce_user reversed %}


          <div class="col-sm-12 col-md-4 col-lg-3" style="margin-top: 1em;">
            <div class="card h-100 ">
              <a href="{% url 'details_annonce' i.id %}">
                <img src="{{i.img_annonce.url}}" class="card-img-top" alt="..." height="200px" /></a>
              <div class="card-body">
                <h5 class="card-title">{{i.desi_annonce}}</h5>
                <p class="card-text">
                  <!-- {{i.description|truncatewords:10}} <br>-->
                </p>
                <p>prix : {{i.prix_annonce}} FG</p>
                <p class="text-danger">{{i.nature}} </p>
              </div>
              <div class="card-footer text-center bg-dark">

                <button class="btn-danger text-center">
                  <a href="{% url 'modif' i.id %}" class="card-link " style="color: white; ">Modifier</a>

                </button>
                <button class=" btn-warning text-center">
                  <a href="{% url 'supp' i.id %}" class="card-link " style="color: white; ">Suppr</a>

                </button>
              </div>
            </div>
          </div>




          {% endfor %}


        </div>
    </div>
  </div>
</div>


<!-- Modal change information personelle-->
<div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="background-color:  rgb(21, 19, 31);">
      <div class="modal-header bg-dark text-center ">
        <h5 class="modal-title text-center text-white " id="exampleModalLabel"> VOS INFORMATIONS</h5>
        <button type="button" class="btn-close bg-danger" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'changer_photo' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-body">


          <label for="profile">Photo de profile</label>
          <input type="file" name="profile" id="" class="form-control" value="{{user_connect.profil.url}}">

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

          <input type="submit" value="Changer" class="btn btn-primary">
        </div>
      </form>
    </div>
  </div>
</div>

<!--fin modal change-->



{% include 'footer.html'%}
{% endblock %}